server:
  port: ${PORT:8080}

spring:
  application:
    name: cloudbox-storage

  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  kafka:
    bootstrap-servers: kafka.railway.internal:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: cloudbox-storage
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

jwt:
  secret: ${mysecretkeymysecretkeymysecretkey123456}
  expiration: ${86400000}

minio:
  endpoint: ${S3_ENDPOINT:https://storage.yandexcloud.net}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  bucket: doiki